name: Optimize Images (overwrite)
on:
  push:
    paths:
      - 'Images/**'
jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compress JPEGs
        uses: calibreapp/image-actions@main
        with:
          jpegQuality: '85'
          webpQuality: '85'
          ignorePaths: 'node_modules/**,build/**'
          # Ключевая опция: не создавать новые файлы с суффиксом, а заменять оригиналы
          compressOnly: true